### ISSUE TITLE
English translation?

### ISSUE THREAD

**Issue by k2arim99** [CuteLand/dogeland#5]
I think it would greatly augment the accessibility of this very interesting proyect, even a machine translation would be a start I think

**Comment by 0xlne** [comment]
I'd appreciate if that request from @k2arim99 would be considered.

**Comment by purofle** [comment]
You can try use Google translation and then pull request

**Comment by Flytreels** [comment]
@k2arim99 Sorry, I will add later

**Comment by Flytreels** [comment]
Now it has been updated https://github.com/CuteLand/dogeland/releases/tag/1.4.1 @0xlne @k2arim99
